name: Build master binaries

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            target: linux

          - os: windows-2022
            target: windows

          - os: macos-10.15
            target: macos

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies (Linux)
        if: matrix.target == 'linux'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Build CLI (non-Windows)
        if: matrix.target != 'windows'
        env:
          CGO_ENABLED: 0
        run: |
          go build -o ./build/dsl ./cmd

      - name: Build CLI (Windows)
        if: matrix.target == 'windows'
        env:
          CGO_ENABLED: 0
        run: |
          go build -o .\build\dsl.exe .\cmd

      - name: Build GUI (Linux)
        if: matrix.target == 'linux'
        run: |
          go build -tags gui -o ./build/dsl-gui ./cmd

      - name: Build GUI (Windows)
        if: matrix.target == 'windows'
        run: |
          go build -tags gui -ldflags="-H windowsgui" -o .\build\dsl-gui.exe .\cmd
          Copy-Item -Recurse "$(go env GOPATH)\pkg\mod\github.com\webview\webview@*\" webview
          Remove-Item -Recurse -Force .\webview\dll
          .\webview\script\build.bat
          Copy-Item .\webview\dll\x64\*.dll .\build\

      - name: Build GUI (macOS)
        if: matrix.target == 'macos'
        run: |
          mkdir -p ./build/dsl-gui.app/Contents/MacOS
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleExecutable</key>
            <string>dsl-gui</string>
            <key>CFBundleIdentifier</key>
            <string>eu.3e8.go.dsl</string>
          </dict>
          </plist>' > ./build/dsl-gui.app/Contents/Info.plist
          go build -tags gui -o ./build/dsl-gui.app/Contents/MacOS/dsl-gui ./cmd

      - name: Zip (non-Windows)
        if: matrix.target != 'windows'
        run: |
          cd ./build
          zip -0 -r build.zip ./*

      - name: Zip (Windows)
        if: matrix.target == 'windows'
        run: |
          Set-Location .\build
          Compress-Archive -CompressionLevel NoCompression .\* build.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./build/build.zip

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine variables
        id: vars
        shell: bash
        env:
          TZ: UTC0
        run: |
          echo "version=master-$(git log -1 --format='%cd-%h' --date='format-local:%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "archivename=dsl-master-$(git log -1 --format='%cd-%h' --date='format-local:%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "time=$(git log -1 --format='%cd' --date='format-local:%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Prepare common files
        run: |
          mkdir -p ./build/template
          echo "${{ steps.vars.outputs.version }}" > ./build/template/VERSION
          cp LICENSE ./build/template/
          cp ./cmd/LICENSE-3RD-PARTY ./build/template/
          cp README.md ./build/template/
          cp ./cmd/README-config.md ./build/template/

      - name: Install pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>$pagetitle$</title>
            <style type="text/css">
            html { margin: 0 2em; background: #fff; color: #000; }
            body { line-height: 1.6; max-width: 45em; margin: 3em auto; font-size: 17px;
                   font-family: Georgia, Palatino, Cambria, serif; }
            a { color: #07f; text-decoration: none; }
            a:hover { text-decoration: underline; }
            pre, code { background: #f0f0f0; border-radius: .5em; }
            pre { padding: .75em 1em; overflow-x: auto; }
            code { padding: .2em .3em; font-size: 80%;
                   font-family: Menlo, Monaco, "Lucida Console", Consolas, monospace; }
            pre code { padding: 0; }
            li { margin: .5em 0; }
            @media (prefers-color-scheme: dark) {
              html { background: #000; color: #ddd; }
              a { color: #39f; }
              pre, code { background: #2f2f2f; }
            }
            </style>
          </head>
          <body>
          $body$
          </body>
          </html>' > ./build/pandoc.html
          for doc in ./build/template/*.md; do
            out="${doc%.*}.html"
            pandoc "$doc" -f markdown -t html5 --template=./build/pandoc.html -o "$out"
          done

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Build archives
        shell: bash
        run: |
          cd ./build
          for artifact in ../artifacts/*/; do
            target="$(basename "$artifact")"
            cp -r ./template "./${{ steps.vars.outputs.archivename }}-$target"
            unzip "../artifacts/$target/build.zip" -d "./${{ steps.vars.outputs.archivename }}-$target/"
            zip -r "${{ steps.vars.outputs.archivename }}-$target.zip" "${{ steps.vars.outputs.archivename }}-$target"
          done

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: github-master-builds
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          artifacts: "./build/*.zip"
          artifactContentType: application/zip
          name: Auto-built binaries
          body: |
            These binaries are automatically built from the master branch.\
            Current version: ${{ github.sha }} (${{ steps.vars.outputs.time }})
            
            Select the build for your platform from the assets below.
            
            *Note: If you want to get the corresponding source code please use Git.\
            The source archives linked below don't contain the actual source.*
